# Generated by Django 4.1.3 on 2022-12-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_alter_shippingaddress_email_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=10000),
        ),
    ]
